// eslint-disable-next-line @typescript-eslint/no-require-imports
const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./src/**/*.{ts,tsx}",
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
   corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      backgroundImage: {
        "login-banner": "url('/assets/images/banner_login.png')",
      },
      colors: {
        primary: {
          50: "#f1effb",
          100: "#c7c0e3",
          200: "#9791af",
          300: "#685e8a",
          400: "#4a3f73",
          500: "#1d0f50",
          600: "#1a0e49",
          700: "#150b39",
          800: "#10082c",
          900: "#0c0622",
        },
        "secondary/orange": {
          25: "#fffcf5",
          50: "#fffaeb",
          100: "#ffeec1",
          200: "#ffe6a3",
          300: "#ffdb78",
          400: "#ffd45e",
          500: "#ffc936",
          600: "#e8b731",
          700: "#b58f26",
          800: "#8c6f1e",
          900: "#6b5417",
        },
        "secondary/teal": {
          50: "#eefdf9",
          100: "#cbf8ec",
          200: "#b2f5e3",
          300: "#8ff1d7",
          400: "#79eecf",
          500: "#58eac3",
          600: "#50d5b1",
          700: "#3ea68a",
          800: "#30816b",
          900: "#256252",
        },
        "secondary/purple": {
          50: "#f7f4ff",
          100: "#e7defe",
          200: "#dbcdfe",
          300: "#cab7fe",
          400: "#c0a9fd",
          500: "#b093fd",
          600: "#8D6AEB",
          700: "#7d68b4",
          800: "#61518b",
          900: "#4a3e6a",
        },
        neutral: {
          50: "#ebecee",
          100: "#c0c4cb",
          200: "#a2a8b1",
          300: "#77808e",
          400: "#5d6878",
          500: "#344256",
          600: "#2f3c4e",
          700: "#252f3d",
          800: "#1d242f",
          900: "#161c24",
        },
        red: {
          50: "#ffebeb",
          100: "#ffc1c1",
          200: "#ffa3a3",
          300: "#ff7979",
          400: "#ff5f5f",
          500: "#ff3737",
          600: "#e83232",
          700: "#b52727",
          800: "#8c1e1e",
          900: "#6b1717",
        },
        yellow: {
          50: "#fffceb",
          100: "#fff5c1",
          200: "#fff0a3",
          300: "#ffea78",
          400: "#ffe55e",
          500: "#ffdf36",
          600: "#e8cb31",
          700: "#b59e26",
          800: "#8c7b1e",
          900: "#6b5e17",
        },
        green: {
          25: "#f6fffd",
          50: "#e7f8f1",
          100: "#b5ead4",
          200: "#91dfbf",
          300: "#5eda11",
          400: "#3fc88f",
          500: "#0fba73",
          600: "#0ea969",
          700: "#0b8452",
          800: "#08663f",
          900: "#064e30",
        },
        "text/purple": "#7d68b4",
        White: "#fdfdff",
        "Light-Grey": "#a2a8b1",
        "Dark-Grey": "#5D6878",
        Black: "#0D253C",
        B0: "#fdfdff",
        B10: "#f8f8f8",
        B20: "#f5f6f7",
        B30: "#ebedf0",
        B800: "#15294B",
        "Dark-Surface": "#FDFDFF",
        "Light-Surface": "#5d6878",
        transparent: "transparent",
      },
      fontSize: {
        h1: ["3.5rem", { lineHeight: "5.25rem", fontWeight: "400" }],
        h2: ["3rem", { lineHeight: "4.5rem", fontWeight: "400" }],
        h3: ["2.5rem", { lineHeight: "3.75rem", fontWeight: "400" }],
        h4: ["2rem", { lineHeight: "3rem", fontWeight: "400" }],
        "h1-bold": ["3.5rem", { lineHeight: "5.25rem", fontWeight: "700" }],
        "h2-bold": ["3rem", { lineHeight: "4.5rem", fontWeight: "700" }],
        "h3-bold": ["2.5rem", { lineHeight: "3.75rem", fontWeight: "700" }],
        "h4-bold": ["2rem", { lineHeight: "3rem", fontWeight: "700" }],
        "title-1": ["1.75rem", { lineHeight: "2.625rem", fontWeight: "400" }],
        "title-2": ["1.5rem", { lineHeight: "2.25rem", fontWeight: "400" }],
        "title-1-bold": [
          "1.75rem",
          { lineHeight: "2.625rem", fontWeight: "700" },
        ],
        "title-2-bold": [
          "1.5rem",
          { lineHeight: "2.25rem", fontWeight: "700" },
        ],
        "body-1": ["1.25rem", { lineHeight: "1.875rem", fontWeight: "400" }],
        "body-2": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-1-bold": [
          "1.25rem",
          { lineHeight: "1.875rem", fontWeight: "700" },
        ],
        "body-2-bold": ["1rem", { lineHeight: "1.5rem", fontWeight: "700" }],
        "small-1": ["0.875rem", { lineHeight: "1.313rem", fontWeight: "400" }],
        "small-1-medium": [
          "0.875rem",
          { lineHeight: "1.313rem", fontWeight: "500" },
        ],
        "small-1-bold": [
          "0.875rem",
          { lineHeight: "1.313rem", fontWeight: "700" },
        ],
        micro: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "micro-bold": [
          "0.75rem",
          { lineHeight: "1.125rem", fontWeight: "700" },
        ],
        local: ["0.625rem", { lineHeight: "0.938rem", fontWeight: "400" }],
        "local-bold": [
          "0.625rem",
          { lineHeight: "0.938rem", fontWeight: "700" },
        ],
      },
      spacing: {
        "spacing-tiny": "0.25rem",
        "spacing-x-small": "0.5rem",
        "spacing-small": "0.75rem",
        "spacing-med": "1rem",
        "spacing-large": "1.5rem",
        "spacing-x-large": "2rem",
        "spacing-xx-large": "2.5rem",
        "spacing-xxx-large": "3rem",
        "spacing-jumbo": "3.5rem",
        "spacing-x-jumbo": "4rem",
        "spacing-xx-jumbo": "5rem",
        "spacing-xxx-jumbo": "6rem",
      },
      borderRadius: {
        "rad-small": "0.5rem",
        "rad-large": "1.25rem",
        "rad-full": "62.4375rem",
      },
      gridTemplateColumns: {
        ...defaultTheme.gridTemplateColumns,
        "custom-grid": "repeat(12, 102px)",
      },
      boxShadow: {
        0.5: "0px 1px 10px 3px #0000000D",
        "1.0": "0px 1px 10px 5px #0000001A",
        "2.0": "0px 6px 10px 2px #00000033",
        "3.0": "0px 6px 10px 3px #0000004D",
        "4.0": "0px 6px 10px 4px #00000066",
      },
      keyframes: {
        ...defaultTheme.keyframes,
        "fade-in-down": {
          "0%": {
            opacity: 0,
            height: 0,
            display: "hidden",
          },
          "20%": {
            height: 20,
            opacity: 0,
            display: "flex",
          },
          "50%": {
            height: 50,
            opacity: 50,
            display: "flex",
            overflow: "hidden",
          },
          "80%": {
            height: 80,
            opacity: 80,
            display: "flex",
            overflow: "hidden",
          },
          "90%": {
            height: 90,
            opacity: 90,
            display: "flex",
            overflow: "hidden",
          },
          "100%": {
            height: 100,
            opacity: 100,
            display: "flex",
          },
        },
        "fade-in-up": {
          "0%": {
            opacity: 100,
            display: "flex",
            height: 100,
          },
          "20%": {
            height: 80,
            opacity: 80,
            overflow: "hidden",
          },
          "50%": {
            height: 50,
            opacity: 50,
            display: "flex",
            overflow: "hidden",
          },
          "80%": {
            height: 20,
            opacity: 0,
            overflow: "hidden",
            display: "flex",
          },
          "100%": {
            display: "hidden",
            opacity: 0,
            height: 0,
          },
        },
        "fade-in-right": {
          "0%": {
            opacity: 0,
            width: 0,
            overflow: "hidden",
          },
          "100%": {
            opacity: 100,
            width: 100,
            overflow: "hidden",
          },
        },
        "fade-in": {
          "0%": {
            opacity: 0,
          },
          "100%": {
            opacity: 100,
          },
        },
        "fade-out": {
          "0%": {
            opacity: 100,
          },
          "100%": {
            opacity: 0,
            display: "hidden",
          },
        },
        "fade-out-left": {
          "0%": {
            opacity: 100,
            width: 100,
            overflow: "hidden",
          },
          "20%": {
            opacity: 80,
            width: 80,
            overflow: "hidden",
          },
          "50%": {
            opacity: 50,
            width: 50,
            overflow: "hidden",
          },
          "80%": {
            opacity: 20,
            width: 20,
            overflow: "hidden",
          },
          "100%": {
            opacity: 0,
            width: "0%",
            overflow: "hidden",
            display: "hidden",
          },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "children-accordion-opened": {
          "0%": {
            display: "none",
            opacity: 0,
            height: 0,
            overflow: "hidden",
            visibility: "hidden",
          },
          "50%": {
            opacity: 1,
            height: "50%",
            overflow: "hidden",
            visibility: "visible",
          },
          "100%": {
            opacity: 1,
            overflow: "auto",
            height: "100%",
            visibility: "visible",
          },
        },
        "children-accordion-closed": {
          "0%": {
            opacity: 1,
            height: "100%",
            overflow: "hidden",
            visibility: "visible",
          },
          "50%": {
            opacity: 0.5,
            height: "50%",
            overflow: "hidden",
            visibility: "visible",
          },
          "100%": {
            overflow: "hidden",
            opacity: 0,
            height: 0,
            visibility: "hidden",
            display: "none",
          },
        },
      },
      animation: {
        ...defaultTheme.animation,
        "fade-opened": "fade-in-down 0.3s ease-out",
        "fade-closed": "fade-in-up 0.3s ease-out",
        "fade-nav-opened": "fade-in-right 0.3s ease-in",
        "fade-interaction-accepted": "fade-in-right 0.5s ease-in-out",
        "fade-nav-closed": "fade-out-left 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-in",
        "fade-out": "fade-out 0.3s ease-out",
        "children-content-accordion-opened":
          "children-accordion-opened 0.4s 1 linear forwards",
        "children-content-accordion-closed":
          "children-accordion-closed 0.4s 1 linear forwards",
        blink: "blink 1s infinite",
      },
    },
  },
  plugins: [],
  prefix: 'tw-',
};
